### ISSUE TITLE
commander does not directly execute to change theme

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode-commander#70]
Testing #51

I thought commander would execute command on behalf of me and could actually change the theme color if I have provided the exact name of some theme. It seems to fail to directly execute the command but rather just provide me with options.
![Image](https://github.com/user-attachments/assets/a4be9998-e663-4d10-af4e-b986f1100b78)

and then I would get 
```
I attempted to change the theme to "Monokai". The command to select the theme was executed, but there was an issue updating the settings directly. You can manually select the "Monokai" theme by using the keybinding `Cmd+K Cmd+T
```

Commander agent does successfully open and focuses the "correct file" if I were to say something like:
```
@commander show me my files
```

**Comment by benibenj** [comment]
Seems to work most of the time for me. Closing for now
